### ISSUE TITLE
Hiero breaks on loading Effect Json

### ISSUE THREAD

**Issue by jrsndl** [ynput/ayon-hiero#34]
### Is there an existing issue for this?

- [x] I have searched the existing issues and added correct labels.

## Current Behavior
After loading published effect to the timeline, Loader and Manager windows are empty

![Image](https://github.com/user-attachments/assets/05e8ff91-3a57-4471-a4c6-4cb1618738ac)

## Expected Behavior
Effect loader should work

### Steps To Reproduce:

1. Make fresh Hiero workfile, load several Nuke renders
2. Load effect
3. Loader and Manage are now empty, see console for error

### Version
server 1.54, core 1.09, Hiero 0.40

### What platform were you running when you found the bug?
Windows

```
WARNING:EventCallback:Failed to execute event callback < EventCallback - _on_folders_selection_change > C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\ui\products_widget.py
Traceback (most recent call last):
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\lib\events.py", line 332, in process_event
    callback(event)
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\ui\products_widget.py", line 458, in _on_folders_selection_change
    self._refresh_model()
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\ui\products_widget.py", line 323, in _refresh_model
    self._products_model.refresh(
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\ui\products_model.py", line 480, in refresh
    product_items = self._controller.get_product_items(
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\control.py", line 202, in get_product_items
    return self._products_model.get_product_items(
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\models\products.py", line 229, in get_product_items
    self._refresh_product_items(
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\models\products.py", line 617, in _refresh_product_items
    product_items_by_id = self._query_product_items_by_ids(
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\models\products.py", line 537, in _query_product_items_by_ids
    return self._create_product_items(
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\models\products.py", line 463, in _create_product_items
    loaded_product_ids = self._controller.get_loaded_product_ids()
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\tools\loader\control.py", line 374, in get_loaded_product_ids
    for container in containers:
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\hiero_0.4.0\ayon_hiero\api\pipeline.py", line 166, in ls
    container_data = parse_container(item)
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\hiero_0.4.0\ayon_hiero\api\pipeline.py", line 227, in parse_container
    container = data_to_container(item, obj_data)
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\hiero_0.4.0\ayon_hiero\api\pipeline.py", line 197, in data_to_container
    schema.validate(data)
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\addons\core_1.0.9\ayon_core\pipeline\schema\__init__.py", line 56, in validate
    jsonschema.validate(data,
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\jsonschema\validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "C:\Users\jiri.sindelar\AppData\Local\Ynput\AYON\dependency_packages\ayon_2406251801_windows.zip\dependencies\jsonschema\validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: 'ayon:container-2.0' is not one of ['openpype:container-2.0']

Failed validating 'enum' in schema['properties']['schema']:
    {'description': 'Schema identifier for payload',
     'enum': ['openpype:container-2.0'],
     'example': 'openpype:container-2.0',
     'type': 'string'}

On instance['schema']:
    'ayon:container-2.0'
```

### Relevant log output:

```shell

```

**Comment by jakubjezek001** [comment]
@jrsndl it seems to me this is not relevant anymore, right?
